flowchart LR
  src_application["src.application"] -->|218| domain_domain["domain.domain"]
  src_interfaces["src.interfaces"] -->|124| src_application["src.application"]
  src_application["src.application"] -->|112| src_infrastructure["src.infrastructure"]
  src_application_ledger["src.application.ledger"] -->|55| domain_domain["domain.domain"]
  src_application_ledger["src.application.ledger"] -->|39| domain_domain_ledger["domain.domain.ledger"]
  src_application["src.application"] -->|32| domain_storage["domain.storage"]
  scripts["scripts"] -->|31| src_application["src.application"]
  src_application["src.application"] -->|29| domain_domain_engine["domain.domain.engine"]
  src_application_research["src.application.research"] -->|26| src_application["src.application"]
  src_application_trades["src.application.trades"] -->|26| domain_domain["domain.domain"]
  src_application["src.application"] -->|23| src_application_ledger["src.application.ledger"]
  src_application_positions["src.application.positions"] -->|23| src_application["src.application"]
  src_application_inbound["src.application.inbound"] -->|21| src_application["src.application"]
  src_application_trades["src.application.trades"] -->|20| src_application["src.application"]
  src_application_multi_tick["src.application.multi_tick"] -->|18| src_application["src.application"]
  src_application_trades["src.application.trades"] -->|18| src_application_ledger["src.application.ledger"]
  src_application_trades["src.application.trades"] -->|16| src_infrastructure["src.infrastructure"]
  src_application["src.application"] -->|15| src_application_multi_tick["src.application.multi_tick"]
  src_application["src.application"] -->|15| src_application_settings["src.application.settings"]
  src_application["src.application"] -->|14| src_application_positions["src.application.positions"]
  src_application_positions["src.application.positions"] -->|13| domain_domain["domain.domain"]
  src_infrastructure["src.infrastructure"] -->|13| src_application["src.application"]
  domain_domain["domain.domain"] -->|12| domain_domain_ledger["domain.domain.ledger"]
  src_application["src.application"] -->|12| domain_domain_ledger["domain.domain.ledger"]
  src_interfaces["src.interfaces"] -->|10| src_application_trades["src.application.trades"]
  src_application_ledger["src.application.ledger"] -->|9| src_infrastructure["src.infrastructure"]
  src_application["src.application"] -->|8| src_application_trades["src.application.trades"]
  src_application_multi_tick["src.application.multi_tick"] -->|7| src_infrastructure["src.infrastructure"]
  src_application_positions["src.application.positions"] -->|7| domain_domain_ledger["domain.domain.ledger"]
  src_application_positions["src.application.positions"] -->|7| domain_storage["domain.storage"]
  src_application_trades["src.application.trades"] -->|7| domain_domain_ledger["domain.domain.ledger"]
  domain_domain_ledger["domain.domain.ledger"] -->|6| domain_domain["domain.domain"]
  src_application_ledger["src.application.ledger"] -->|6| src_application["src.application"]
  src_application_multi_tick["src.application.multi_tick"] -->|6| domain_domain["domain.domain"]
  src_application_positions["src.application.positions"] -->|6| src_infrastructure["src.infrastructure"]
  src_interfaces["src.interfaces"] -->|6| src_application_research["src.application.research"]
  domain_services["domain.services"] -->|5| domain_domain["domain.domain"]
  src_application_research["src.application.research"] -->|5| src_application_ledger["src.application.ledger"]
  src_application_setup["src.application.setup"] -->|5| src_application["src.application"]
  src_interfaces["src.interfaces"] -->|5| src_application_ledger["src.application.ledger"]
  src_interfaces["src.interfaces"] -->|5| src_infrastructure["src.infrastructure"]
  domain_domain["domain.domain"] -->|4| domain_domain_engine["domain.domain.engine"]
  scripts["scripts"] -->|4| src_application_research["src.application.research"]
  scripts["scripts"] -->|4| src_infrastructure["src.infrastructure"]
  src_application_positions["src.application.positions"] -->|4| src_application_ledger["src.application.ledger"]
  src_application_research["src.application.research"] -->|4| src_application_trades["src.application.trades"]
  src_application_settings["src.application.settings"] -->|4| src_application["src.application"]
  src_interfaces["src.interfaces"] -->|4| src_application_settings["src.application.settings"]
  scripts["scripts"] -->|3| src_application_ledger["src.application.ledger"]
  src_application["src.application"] -->|3| domain_services["domain.services"]
  src_application["src.application"] -->|3| src_application_research["src.application.research"]
  src_application_inbound["src.application.inbound"] -->|3| src_infrastructure["src.infrastructure"]
  src_infrastructure["src.infrastructure"] -->|3| domain_domain["domain.domain"]
  src_interfaces["src.interfaces"] -->|3| src_application_positions["src.application.positions"]
  domain_domain_engine["domain.domain.engine"] -->|2| domain_domain["domain.domain"]
  domain_services["domain.services"] -->|2| domain_storage["domain.storage"]
  scripts["scripts"] -->|2| domain_domain["domain.domain"]
  src_application_ledger["src.application.ledger"] -->|2| src_application_settings["src.application.settings"]
  src_application_multi_tick["src.application.multi_tick"] -->|2| domain_storage["domain.storage"]
  src_application_trades["src.application.trades"] -->|2| src_application_positions["src.application.positions"]
  domain_storage["domain.storage"] -->|1| domain_domain["domain.domain"]
  src_application["src.application"] -->|1| src_application_setup["src.application.setup"]
  src_application_inbound["src.application.inbound"] -->|1| domain_domain["domain.domain"]
  src_application_inbound["src.application.inbound"] -->|1| src_application_settings["src.application.settings"]
  src_application_multi_tick["src.application.multi_tick"] -->|1| domain_services["domain.services"]
  src_application_positions["src.application.positions"] -->|1| src_application_trades["src.application.trades"]
  src_application_research["src.application.research"] -->|1| domain_domain["domain.domain"]
  src_application_research["src.application.research"] -->|1| domain_domain_ledger["domain.domain.ledger"]
  src_application_research["src.application.research"] -->|1| src_application_settings["src.application.settings"]
  src_application_setup["src.application.setup"] -->|1| src_application_settings["src.application.settings"]
  src_application_setup["src.application.setup"] -->|1| src_infrastructure["src.infrastructure"]
  src_interfaces["src.interfaces"] -->|1| domain_domain_ledger["domain.domain.ledger"]
  src_interfaces["src.interfaces"] -->|1| src_application_inbound["src.application.inbound"]
  src_interfaces["src.interfaces"] -->|1| src_application_setup["src.application.setup"]
